language: go
go:
- 1.11.1
env:
  global:
  - GO15VENDOREXPERIMENT=1
  - GOOS=linux
before_install:
- go get -u github.com/golang/dep/cmd/dep
install:
- "$GOPATH/bin/dep ensure"
- go build .
script:
- md5sum docker-zfs-plugin > md5.txt
- sha256sum docker-zfs-plugin > sha256.txt
- sha512sum docker-zfs-plugin > sha512.txt
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Glbh1DubmfEe7zNPQEgv6xgh2y2+PyRJ+pLlozzaNTbwWnSYd/uDJc1etRkK+bM/64hUd9oszobNqMuzEuJSXBH4ibn2hUb6AMw+saY57aaBKCCPXwYmEGpe2oby+9mAJp4BYjAtyRDBL95nwIn9WnP3sqSe59pmmNNakf0dAHp2Ny1CBLQv3KkwMlJcLLrTWqn99+KkFJ4TLZ8Y+XlJ/Dse81QPBLLxT6bZi/+43Q8aUXVZ3yLLr5bUWJGhPeyM0fW4J492BFnRxmod5M+a+JgRtb5pYOAQKzS1taa9JxV0BI2qkjMhXWGhkNIin8WP/2uLkQLA4/4q8JsnULzILRhN9cx0ihPrabROMQ9RpxWIPsL+ccQ/VD6lB8cgMOUbmO6H8vExKNelkHNKgV+KsbaBEp63bTKgx87IzMRzBfoxSDh5JNwixQlzjDnu/uW1plW2R5pmQoA69eviGI39LpyAzNREeCZDEQ9HfVnJfopzNEaPbBQGS75ZTTZNH/Iy79+py21NUKjCTXNV0lFTTjMGZ32jJ6qNtM29BdAFWGirqnhBKA2TI2nKumo5+KP2dJnen++vYrqf/QrEtqQiWlBEWWliVQ60kQ0zNbTnyNu0sikZaW3+USMyFfv2jjvuWKRn/oXXHUjiLFABbGPa0BElWRAoFBAcBNlZRVpLCSU=
  file:
  - docker-zfs-plugin
  - md5.txt
  - sha256.txt
  - sha512.txt
  on:
    tags: true
